import os

content = []
content.append('import { createClient } from "@supabase/supabase-js";')
content.append('')
content.append('const supabaseUrl = process.env.SUPABASE_URL || "https://nualwgobuhklnoaeawrz.supabase.co";')
content.append('const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || "";')
content.append('const supabase = createClient(supabaseUrl, supabaseKey);')
content.append('')
content.append('export default async function handler(req: any, res: any) {')
content.append('  res.setHeader("Access-Control-Allow-Origin", "*");')
content.append('  res.setHeader("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, PATCH, OPTIONS");')
content.append('  res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");')
content.append('')
content.append('  if (req.method === "OPTIONS") {')
content.append('    return res.status(200).end();')
content.append('  }')
content.append('')
content.append('  const url = new URL(req.url || "/", "http://localhost");')
content.append('  const path = url.pathname;')
content.append('')
content.append('  try {')
content.append('    if (path === "/api/books" && req.method === "GET") {')
content.append('      const { data, error } = await supabase.from("books").select("*").order("id", { ascending: true });')
content.append('      if (error) throw error;')
content.append('      return res.status(200).json(data || []);')
content.append('    }')
content.append('')
content.append('    if (path === "/api/podcasts/latest") {')
content.append('      const { data, error } = await supabase.from("podcasts").select("*").order("published_at", { ascending: false }).limit(3);')
content.append('      if (error) throw error;')
content.append('      return res.status(200).json(data || []);')
content.append('    }')
content.append('')
content.append('    if (path.startsWith("/api/pages/")) {')
content.append('      const pageName = path.replace("/api/pages/", "");')
content.append('      const { data, error } = await supabase.from("site_pages").select("*").eq("page_name", pageName).maybeSingle();')
content.append('      if (error) throw error;')
content.append('      return res.status(200).json(data);')
content.append('    }')
content.append('')
content.append('    if (path === "/api/healthz") {')
content.append('      return res.status(200).json({ ok: true });')
content.append('    }')
content.append('')
content.append('    return res.status(404).json({ error: "Not found", path });')
content.append('  } catch (err: any) {')
content.append('    console.error("API error:", err);')
content.append('    return res.status(500).json({ error: err.message || "Internal server error" });')
content.append('  }')
content.append('}')
content.append('')

path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'api', 'index.ts')
with open(path, 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(content))
print('Written ' + path)
